### Login
POST http://localhost:9000/api/login
Content-Type: application/json

{ 
  "cedula": 12073739,
  "password": "arojas"
}

### Buscar 1 camión
GET http://localhost:9000/api/camion/259
Content-Type: application/json
 

### Todos los camiones
GET http://localhost:9000/api/camiones
Content-Type: application/jso
 

### Borrar camión
DELETE http://localhost:9000/api/camion/189
Content-Type: application/json
 

### Todos los colores
GET http://localhost:9000/api/colores
Content-Type: application/json

### Enviar correo
GET http://localhost:9000/api/send-email
Content-Type: application/json
